import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Autogenerate sidebars for each plugin based on folder structure
  dialogMenusSidebar: [{ type: 'autogenerated', dirName: 'DialogMenus' }],
  easyScriptSidebar: [{ type: 'autogenerated', dirName: 'EasyScript' }],
  worldSystemSidebar: [{ type: 'autogenerated', dirName: 'WorldSystem' }],
  artifactsSidebar: [{ type: 'autogenerated', dirName: 'Artifacts' }],
};

export default sidebars;
