name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    defaults:
      run:
        working-directory: ariskrisen-docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # Use the lockfile in the subdirectory for cache hashing
          cache-dependency-path: ariskrisen-docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ariskrisen-docs/build

          # This workflow will push the built site to the `gh-pages` branch
          # Make sure to configure GitHub pages to serve from the `gh-pages` branch.
